on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Echo a message
      - name: "Testing GitHub Actions"
        run: echo "Running GitHub Actions Workflow"

      # Step 2: List folder contents before checkout
      - name: "Before listing folder contents"
        run: ls

      # Step 3: Check out the repository
      - uses: actions/checkout@v3

      # Step 4: List folder contents after checkout
      - name: "After listing folder contents"
        run: ls -a

      # Step 5: Log in to DockerHub
      - name: "Login to DockerHub"
        run: docker login --username "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_TOKEN }}"

      # Step 6: Ensure Docker service is running
      - name: "Start Docker Service"
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker

      # Step 7: Build the Docker image
      - name: "Building Docker image"
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-image-creation .

      # Step 8: Push the Docker image to DockerHub
      - name: "Pushing Docker image to DockerHub"
        run: docker push ${{ secrets.DOCKER_USERNAME }}/docker-image-creation
